openapi: 3.1.0

info:
  title: ZorgAPIs API
  version: 0.2.0
  description:
    $ref: './info#description.md'
  license:
    name: MIT License
    url: https://choosealicense.com/licenses/mit/
    
security:
  - oauth2: []

tags:
  # users
  - name: users
    description: Users API
    x-displayName: Users
  - name: user.invitations
    description: User invitations API
    x-displayName: User invitations
  - name: user.memberships
    description: User memberships API
    x-displayName: User memberships
    
  # organizations
  - name: organizations
    description: Organizations API
    x-displayName: Organizations
  - name: organization.invitations
    description: Organization invitations API
    x-displayName: Organization invitations
  - name: organization.memberships
    description: Organization memberships API
    x-displayName: Organization memberships
    
  # api-requirements-versions
  - name: api-requirements-versions
    description: API requirements versions API
    x-displayName: API requirements versions
  - name: api-requirements-version.api-requirements
    description: API requirements version API requirements API
    x-displayName: API requirements version API requirements
    
  # api-specifications
  - name: api-specifications
    description: API specifications API
    x-displayName: API specifications
  - name: api-specification.versions
    description: API specification versions API
    x-displayName: API specification versions
  - name: api-specification.version.urls
    description: API specification version URLs API
    x-displayName: API specification version URLs
  - name: api-specification.version.declarations-of-conformity
    description: API specification version declarations of conformity API
    x-displayName: API specification version declarations of conformity

x-tagGroups:
  - name: Users
    tags:
      - users
      - user.invitations
      - user.memberships
  - name: Organizations
    tags:
      - organizations
      - organization.invitations
      - organization.memberships
  - name: API requirements
    tags:
      - api-requirements-versions
      - api-requirements-version.api-requirements
  - name: API specifications
    tags:
      - api-specifications
      - api-specification.versions
      - api-specification.version.urls
      - api-specification.version.declarations-of-conformity

servers:
  - url: 'https://{environment}.zorgapis.nl/v1alpha2'
    variables:
      environment:
        default: api.sandbox
        enum:
          - api.sandbox

paths:
  # users
  /users/me:
    $ref: './users/_paths/users_me.yaml'
  # users/invitations
  /users/me/invitations:
    $ref: './users/invitations/_paths/invitations.yaml'
  /users/me/invitations/{invitationId}:
    $ref: './users/invitations/_paths/invitations_{invitationId}.yaml'
  /users/me/invitations/{invitationId}:accept:
    $ref: './users/invitations/_paths/invitations_{invitationId}_accept.yaml'
  /users/me/invitations/{invitationId}:decline:
    $ref: './users/invitations/_paths/invitations_{invitationId}_decline.yaml'
  # users/memberships
  /users/me/memberships:
    $ref: './users/memberships/_paths/memberships.yaml'
  /users/me/memberships/{membershipId}:
    $ref: './users/memberships/_paths/memberships_{membershipId}.yaml'
    
  # organizations
  /organizations:
    $ref: './organizations/_paths/organizations.yaml'
  /organizations/{organizationId}:
    $ref: './organizations/_paths/organizations_{organizationId}.yaml'
  # organizations/invitations
  /organizations/{organizationId}/invitations:
    $ref: './organizations/invitations/_paths/invitations.yaml'
  /organizations/{organizationId}/invitations/{invitationId}:
    $ref: './organizations/invitations/_paths/invitations_{invitationId}.yaml'
  /organizations/{organizationId}/invitations/{invitationId}:cancel:
    $ref: './organizations/invitations/_paths/invitations_{invitationId}_cancel.yaml'
  # organizations/memberships
  /organizations/{organizationId}/memberships:
    $ref: './organizations/memberships/_paths/memberships.yaml'
  /organizations/{organizationId}/memberships/{membershipId}:
    $ref: './organizations/memberships/_paths/memberships_{membershipId}.yaml'
    
  # api-requirements-versions
  /api-requirements-versions:
    $ref: './api-requirements-versions/_paths/api-requirements-versions.yaml'
  /api-requirements-versions/{versionName}:
    $ref: './api-requirements-versions/_paths/api-requirements-versions_{versionName}.yaml'
  # api-requirements-versions/api-requirements
  /api-requirements-versions/{versionName}/api-requirements:
    $ref: './api-requirements-versions/api-requirements/_paths/api-requirements.yaml'
    
  # api-specifications
  /api-specifications:
    $ref: './api-specifications/_paths/api-specifications.yaml'
  /api-specifications/{apiSpecificationId}:
    $ref: './api-specifications/_paths/api-specifications_{apiSpecificationId}.yaml'
  # api-specifications/versions
  /api-specifications/{apiSpecificationId}/versions:
    $ref: './api-specifications/versions/_paths/versions.yaml'
  /api-specifications/{apiSpecificationId}/versions/{versionId}:
    $ref: './api-specifications/versions/_paths/versions_{versionId}.yaml'
  # api-specifications/versions/urls
  /api-specifications/{apiSpecificationId}/versions/{versionId}/urls:
    $ref: './api-specifications/versions/urls/_paths/urls.yaml'
  /api-specifications/{apiSpecificationId}/versions/{versionId}/urls/{urlId}:
    $ref: './api-specifications/versions/urls/_paths/urls_{urlId}.yaml'
  # api-specifications/versions/declarations-of-conformity
  /api-specifications/{apiSpecificationId}/versions/{versionId}/declarations-of-conformity:
    $ref: './api-specifications/versions/declarations-of-conformity/_paths/declarations-of-conformity.yaml'
  /api-specifications/{apiSpecificationId}/versions/{versionId}/declarations-of-conformity/{declarationOfConformityId}:
    $ref: './api-specifications/versions/declarations-of-conformity/_paths/declarations-of-conformity_{declarationOfConformityId}.yaml'
    
components:
  # Reusable schemas (data models)
  schemas:
    $ref: './_schemas.yaml'
  # Reusable path, query, header and cookie parameters
  parameters:
    $ref: './_parameters.yaml'
  # Reusable responses, such as 400 Bad Request
  responses:
    $ref: './_responses.yaml'
  # Reusable response headers
  headers:
    $ref: './_headers.yaml'
  # Reusable security schemes
  securitySchemes: 
    $ref: './_securitySchemes.yaml'